[package]
name = "roguelike"
version = "0.1.0"
authors = ["Michael Campagnaro <mikecampo@gmail.com>"]

[dependencies]
rand = "0.3.15"
tcod = { git = "https://github.com/tomassedovic/tcod-rs.git", branch = "master" }
